Add an option to create modals from JSX Elements
vacarsu/uikit-react pull request #49
Opened 2022-03-30 08:16 UTC by Schottkyc137

This PR is a proposal on how one could add modals to the project.

Please review it carefully to make sure it adheres to your code style. I'm not quite sure how to write a test-case for the modals as well

2022-08-24 20:32 UTC, vacarsu commented
Hey sorry it's taken me so long to get to this. Can you add this to the storybook?

2022-08-25 01:41 UTC, vacarsu requested changes

2022-08-25 10:11 UTC, Schottkyc137 commented on src/components/Modal/Modal.tsx
> +  const divElement = document.createElement('div');
I'm not quite sure what you mean by this. The `div` element I'm creating is the container for the modal. Can you show me a more elaborate example of what you mean?

2022-08-25 10:11 UTC, Schottkyc137 commented
> Hey sorry it's taken me so long to get to this. Can you add this to the storybook?

Added it to storybook. Nice to see that you are still maintaining this!

2022-08-25 18:13 UTC, vacarsu approved these changes

2022-08-25 18:15 UTC, vacarsu commented
I pulled the code ran the storybook. I see what you're doing now after looking more thoroughly. Thanks for this!
This closes #34

2022-08-25 18:15 UTC, merged